"""Notifications center — every MQTT event becomes a user-facing notification.

Notifications are generated by the MQTT subscriber (single funnel), stored in
the `notifications` collection, pushed live via WebSocket, and read here.
"""
from datetime import datetime, timezone
from bson import ObjectId
from fastapi import APIRouter, Depends, HTTPException, Query

from ...db import get_db
from ...security import current_user

router = APIRouter(prefix="/notifications", tags=["notifications"])


def _out(n: dict) -> dict:
    return {
        "notification_id": str(n["_id"]),
        "type": n.get("type"),
        "title": n.get("title"),
        "body": n.get("body"),
        "data": n.get("data") or {},
        "read": n.get("read", False),
        "created_at": n["created_at"],
    }


@router.get("")
async def list_notifications(user=Depends(current_user), limit: int = Query(50, le=200)):
    db = get_db()
    q = {"user_id": str(user["_id"])}
    total = await db.notifications.count_documents(q)
    cur = db.notifications.find(q).sort("created_at", -1).limit(limit)
    return {"total": total, "notifications": [_out(n) async for n in cur]}


@router.get("/unread-count")
async def unread_count(user=Depends(current_user)):
    # Fast Redis check: ikiwa count ni 0 na zilizopita zilisomwa, weka cache
    # ndogo ili kila poll isigonge MongoDB (notifications ni nyingi na kila
    # page inapoll mara kwa mara).
    from ...cache import cached
    uid = str(user["_id"])
    async def _load():
        n = await get_db().notifications.count_documents({"user_id": uid, "read": False})
        return {"unread": n}
    # Cache 5s — notification mpya inapokuja, subscriber inabust cache
    return await cached(f"notif:unread:{uid}", _load, ttl=5)


@router.post("/read-all")
async def mark_all_read(user=Depends(current_user)):
    await get_db().notifications.update_many(
        {"user_id": str(user["_id"]), "read": False},
        {"$set": {"read": True, "read_at": datetime.now(timezone.utc)}},
    )
    return {"ok": True}


@router.post("/{notification_id}/read")
async def mark_read(notification_id: str, user=Depends(current_user)):
    try:
        nid = ObjectId(notification_id)
    except Exception:
        raise HTTPException(400, "Invalid notification ID")
    r = await get_db().notifications.update_one(
        {"_id": nid, "user_id": str(user["_id"])},
        {"$set": {"read": True, "read_at": datetime.now(timezone.utc)}},
    )
    if not r.matched_count:
        raise HTTPException(404, "Notification not found")
    return {"ok": True}
