"""Notifications center — every MQTT event becomes a user-facing notification.

Notifications are generated by the MQTT subscriber (single funnel), stored in
the `notifications` collection, pushed live via WebSocket, and read here.
"""
from datetime import datetime, timezone
from typing import Optional
from bson import ObjectId
from fastapi import APIRouter, Depends, HTTPException, Query
from pydantic import BaseModel

from ...db import get_db
from ...security import current_user

router = APIRouter(prefix="/notifications", tags=["notifications"])


def _out(n: dict) -> dict:
    return {
        "notification_id": str(n["_id"]),
        "type": n.get("type"),
        "title": n.get("title"),
        "body": n.get("body"),
        "data": n.get("data") or {},
        "read": n.get("read", False),
        "created_at": n["created_at"],
    }


@router.get("")
async def list_notifications(user=Depends(current_user), limit: int = Query(50, le=200)):
    db = get_db()
    q = {"user_id": str(user["_id"])}
    total = await db.notifications.count_documents(q)
    cur = db.notifications.find(q).sort("created_at", -1).limit(limit)
    return {"total": total, "notifications": [_out(n) async for n in cur]}


@router.get("/unread-count")
async def unread_count(user=Depends(current_user)):
    # Fast Redis check: ikiwa count ni 0 na zilizopita zilisomwa, weka cache
    # ndogo ili kila poll isigonge MongoDB (notifications ni nyingi na kila
    # page inapoll mara kwa mara).
    from ...cache import cached
    uid = str(user["_id"])
    async def _load():
        n = await get_db().notifications.count_documents({"user_id": uid, "read": False})
        return {"unread": n}
    # Cache 5s — notification mpya inapokuja, subscriber inabust cache
    return await cached(f"notif:unread:{uid}", _load, ttl=5)


@router.post("/read-all")
async def mark_all_read(user=Depends(current_user)):
    await get_db().notifications.update_many(
        {"user_id": str(user["_id"]), "read": False},
        {"$set": {"read": True, "read_at": datetime.now(timezone.utc)}},
    )
    return {"ok": True}


@router.post("/{notification_id}/read")
async def mark_read(notification_id: str, user=Depends(current_user)):
    try:
        nid = ObjectId(notification_id)
    except Exception:
        raise HTTPException(400, "Invalid notification ID")
    r = await get_db().notifications.update_one(
        {"_id": nid, "user_id": str(user["_id"])},
        {"$set": {"read": True, "read_at": datetime.now(timezone.utc)}},
    )
    if not r.matched_count:
        raise HTTPException(404, "Notification not found")
    return {"ok": True}


# ── Push Token Storage ──────────────────────────────────────────────
class PushTokenPayload(BaseModel):
    token: str
    provider: str = "fcm"  # fcm | web-push
    platform: str = "web"  # web | android | ios


class PushSubscriptionPayload(BaseModel):
    endpoint: str
    keys: Optional[dict] = None
    platform: str = "web"


@router.post("/push-token")
async def save_push_token(
    payload: PushTokenPayload,
    user=Depends(current_user),
):
    """Save FCM/Web Push token for the current user."""
    db = get_db()
    uid = str(user["_id"])
    now = datetime.now(timezone.utc)

    # Upsert: replace if token already exists, otherwise insert
    await db.push_tokens.update_one(
        {"token": payload.token},
        {
            "$set": {
                "user_id": uid,
                "provider": payload.provider,
                "platform": payload.platform,
                "updated_at": now,
            },
            "$setOnInsert": {
                "created_at": now,
            },
        },
        upsert=True,
    )

    # Also update user document
    await db.users.update_one(
        {"_id": ObjectId(uid)},
        {
            "$set": {
                "push_token": payload.token,
                "push_provider": payload.provider,
                "push_platform": payload.platform,
                "push_enabled": True,
                "push_updated_at": now,
            }
        },
    )

    return {"ok": True}


@router.post("/push-subscription")
async def save_push_subscription(
    payload: PushSubscriptionPayload,
    user=Depends(current_user),
):
    """Save Web Push subscription for the current user."""
    db = get_db()
    uid = str(user["_id"])
    now = datetime.now(timezone.utc)

    await db.push_tokens.update_one(
        {"endpoint": payload.endpoint},
        {
            "$set": {
                "user_id": uid,
                "provider": "web-push",
                "platform": payload.platform,
                "endpoint": payload.endpoint,
                "keys": payload.keys or {},
                "updated_at": now,
            },
            "$setOnInsert": {
                "created_at": now,
            },
        },
        upsert=True,
    )

    return {"ok": True}


@router.post("/push-token/remove")
async def remove_push_token(user=Depends(current_user)):
    """Remove push token (user opts out of notifications)."""
    db = get_db()
    uid = str(user["_id"])

    await db.push_tokens.delete_many({"user_id": uid})
    await db.users.update_one(
        {"_id": ObjectId(uid)},
        {
            "$set": {
                "push_enabled": False,
                "push_token": None,
            }
        },
    )

    return {"ok": True}
